framework:
  default_locale: en
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - en
    providers:
      loco:
        dsn: '%env(LOCO_DSN)%'
        domains:
          - messages
        locales:
          - en
          - ru
