<?php

namespace App\Tests\Service;

use App\Service\ImageConverter;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ImageConverterTest extends WebTestCase
{
    private string $tmpDir;
    private string $pngIn;
    private string $jpgOut;

    protected function setUp(): void
    {
        parent::setUp();

        $this->tmpDir = sys_get_temp_dir() . '/' . uniqid('test-', true);

        if (!is_dir($this->tmpDir)) {
            mkdir($this->tmpDir);
        }

        $this->pngIn = $this->tmpDir . '/image.png';
        $this->jpgOut = $this->tmpDir . '/image.jpg';

        $image = imagecreate(250, 80);
        $background = imagecolorallocate($image, 0, 255, 0);
        imagesetthickness($image, 5);
        imagepng($image, $this->pngIn);
        imagecolordeallocate($image, $background);
        imagedestroy($image);
    }

    public function testPngToJpg(): void
    {
        $imageConverter = new ImageConverter();
        $imageConverter->pngToJpg(
            in: $this->pngIn,
            out: $this->jpgOut,
            quality: 90,
        );

        self::assertFileExists($this->jpgOut);
    }

    public function tearDown(): void
    {
        unlink($this->pngIn);
        unlink($this->jpgOut);
        rmdir($this->tmpDir);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
