# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwt.signingKey: '%kernel.project_dir%/.jwt-secret.pem'
    app.jwt.verificationKey: '%env(JWT_VERIFICATION_KEY)%'
    app.jwt.issued: 'expert-overflow.loc'
    app.jwt.expires: '+30 day'   # Issuance of a token for 1 hour
    app.jwt.reissue: '+1 day' # Token reissue less than 1 day before expiration

    environment: '%kernel.environment%'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  Lcobucci\JWT\Signer\Rsa\Sha512: ~